### YamlMime:ModuleUnit
uid: learn.pillars-of-a-great-azure-architecture.3-design-for-security
title: Design for security
metadata:
  title: Design for security
  description: Design for security
  ms.date: 09/24/2018
  #TODO: Update with real author name.
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 10
content: |
  [!include[](includes/3-design-for-security.md)]
quiz:
  title: 'Knowledge check - Design for security'
  questions:
  - content: 'Which of the following types of data may need to have security protections?'
    choices:
    - content: 'Customer data that contains personal information'
      isCorrect: false
      incorrectExplanation: 'It is important to provide proper security protections for this data, but this is not the only correct choice.'
    - content: 'Financial data supporting business operations'
      isCorrect: false
      incorrectExplanation: 'It is important to provide proper security protections for this data, but this is not the only correct choice.'
    - content: 'Data containing intellectual property'
      isCorrect: false
      incorrectExplanation: 'It is important to provide proper security protections for this data, but this is not the only correct choice.'
    - content: 'All of the above may need security protections'
      isCorrect: true
      correctExplanation: 'All of the above may merit additional security protections.'
  - content: 'Which of the following is an example of an attack you might see at the perimeter layer?'
    choices:
    - content: 'Exposed credentials posted online'
      isCorrect: false
      incorrectExplanation: 'Exposed credentials are a huge risk to an organization, but are not a permiter attack.'
    - content: 'A SYN flood attack'
      isCorrect: true
      correctExplanation: 'SYN flood attacks are a type of denial-of-service attack that are commonly seen on the network perimeter.'
    - content: 'Door drafting to get into a datacenter'
      isCorrect: false
      incorrectExplanation: 'Door drafting is a physical layer attack.'
    - content: 'Ransomware that encrypts the disks of a virtual machine'
      isCorrect: false
      incorrectExplanation: 'Ransomware attacks are a VM/compute layer attack.'
