### YamlMime:ModuleUnit
uid: learn.create-azure-storage-account.3-choose-your-account-settings
title: <span data-ttu-id="729bc-101">Auswählen der Kontoeinstellungen</span><span class="sxs-lookup"><span data-stu-id="729bc-101">Choose your account settings</span></span>
metadata:
  title: <span data-ttu-id="729bc-102">Auswählen der Kontoeinstellungen</span><span class="sxs-lookup"><span data-stu-id="729bc-102">Choose your account settings</span></span>
  description: <span data-ttu-id="729bc-103">Auswählen der Kontoeinstellungen</span><span class="sxs-lookup"><span data-stu-id="729bc-103">Choose your account settings</span></span>
  ms.openlocfilehash: 2b4b0b6fa5cf2ea927065e28f0e634d4719a5c8b
  ms.sourcegitcommit: c07e11980180ae35cb3485548f81e16152d77781
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/02/2018
  ms.locfileid: "43471884"
durationInMinutes: 7
content: '[!include[](includes/3-choose-your-account-settings.md)]'
