### YamlMime:ModuleUnit
uid: learn.create-azure-storage-account.3-choose-your-account-settings
title: Auswählen der Kontoeinstellungen
metadata:
  title: Auswählen der Kontoeinstellungen
  description: Auswählen der Kontoeinstellungen
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 7
content: |
  [!include[](includes/3-choose-your-account-settings.md)]