### YamlMime:ModuleUnit
uid: learn.scale-and-size-virtual-machines.5-exercise-create-a-scale-set-and-configure-autoscaling
title: 'Übung: Erstellen einer Skalierungsgruppe und Konfigurieren der automatischen Skalierung'
metadata:
  title: 'Übung: Erstellen einer Skalierungsgruppe und Konfigurieren der automatischen Skalierung'
  description: 'Übung: Erstellen einer Skalierungsgruppe und Konfigurieren der automatischen Skalierung'
  ms.openlocfilehash: ca265df828582f0b74003b36a4e33b824a111290
  ms.sourcegitcommit: 4d2d6d8c52fa24ae1c5c06cf4cb3afa09d8c8363
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44254822"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-a-scale-set-and-configure-autoscaling.md)]'
