### YamlMime:ModuleUnit
uid: learn.scale-and-size-virtual-machines.5-exercise-create-a-scale-set-and-configure-autoscaling
title: '<span data-ttu-id="da666-101">Übung: Erstellen einer Skalierungsgruppe und Konfigurieren der automatischen Skalierung</span><span class="sxs-lookup"><span data-stu-id="da666-101">Exercise - Create a scale set and configure autoscaling</span></span>'
metadata:
  title: '<span data-ttu-id="da666-102">Übung: Erstellen einer Skalierungsgruppe und Konfigurieren der automatischen Skalierung</span><span class="sxs-lookup"><span data-stu-id="da666-102">Exercise - Create a scale set and configure autoscaling</span></span>'
  description: '<span data-ttu-id="da666-103">Übung: Erstellen einer Skalierungsgruppe und Konfigurieren der automatischen Skalierung</span><span class="sxs-lookup"><span data-stu-id="da666-103">Exercise - Create a scale set and configure autoscaling</span></span>'
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 5cf3cb0d1bbc8fa928f722f9b0cead96a1aabc68
  ms.sourcegitcommit: 87602488fb13c785daee0e5831ace59668a85d52
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/18/2018
  ms.locfileid: "45992302"
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-a-scale-set-and-configure-autoscaling.md)]'
