### YamlMime:ModuleUnit
uid: learn.scale-and-size-virtual-machines.5-exercise-create-a-scale-set-and-configure-autoscaling
title: Exercise - Create a scale set and configure autoscaling
metadata:
  title: Exercise - Create a scale set and configure autoscaling
  description: Exercise - Create a scale set and configure autoscaling
durationInMinutes: 10
content: |
  [!include[](includes/5-exercise-create-a-scale-set-and-configure-autoscaling.md)]