### YamlMime:ModuleUnit
uid: learn.scale-and-size-virtual-machines.5-exercise-create-a-scale-set-and-configure-autoscaling
title: 'Übung: Erstellen einer Skalierungsgruppe und Konfigurieren der automatischen Skalierung'
metadata:
  title: 'Übung: Erstellen einer Skalierungsgruppe und Konfigurieren der automatischen Skalierung'
  description: 'Übung: Erstellen einer Skalierungsgruppe und Konfigurieren der automatischen Skalierung'
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: a0c8a51ea1f53b0ad09a2e6e1ee76cd7bbebc9a6
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47128990"
azureSandbox: true
durationInMinutes: 20
content: '[!include[](includes/5-exercise-create-a-scale-set-and-configure-autoscaling.md)]'
