### YamlMime:ModuleUnit
uid: learn.scale-and-size-virtual-machines.5-exercise-create-a-scale-set-and-configure-autoscaling
title: 'Übung: Erstellen einer Skalierungsgruppe und Konfigurieren der automatischen Skalierung'
metadata:
  title: 'Übung: Erstellen einer Skalierungsgruppe und Konfigurieren der automatischen Skalierung'
  description: 'Übung: Erstellen einer Skalierungsgruppe und Konfigurieren der automatischen Skalierung'
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 5cf3cb0d1bbc8fa928f722f9b0cead96a1aabc68
  ms.sourcegitcommit: 87602488fb13c785daee0e5831ace59668a85d52
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/18/2018
  ms.locfileid: "45992302"
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-a-scale-set-and-configure-autoscaling.md)]'
