### YamlMime:ModuleUnit
uid: learn.scale-and-size-virtual-machines.5-exercise-create-a-scale-set-and-configure-autoscaling
title: '<span data-ttu-id="453e1-101">Übung: Erstellen einer Skalierungsgruppe und Konfigurieren der automatischen Skalierung</span><span class="sxs-lookup"><span data-stu-id="453e1-101">Exercise - Create a scale set and configure autoscaling</span></span>'
metadata:
  title: '<span data-ttu-id="453e1-102">Übung: Erstellen einer Skalierungsgruppe und Konfigurieren der automatischen Skalierung</span><span class="sxs-lookup"><span data-stu-id="453e1-102">Exercise - Create a scale set and configure autoscaling</span></span>'
  description: '<span data-ttu-id="453e1-103">Übung: Erstellen einer Skalierungsgruppe und Konfigurieren der automatischen Skalierung</span><span class="sxs-lookup"><span data-stu-id="453e1-103">Exercise - Create a scale set and configure autoscaling</span></span>'
  ms.openlocfilehash: ca265df828582f0b74003b36a4e33b824a111290
  ms.sourcegitcommit: 4d2d6d8c52fa24ae1c5c06cf4cb3afa09d8c8363
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44254822"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-a-scale-set-and-configure-autoscaling.md)]'
