### YamlMime:ModuleUnit
uid: learn.scale-and-size-virtual-machines.5-exercise-create-a-scale-set-and-configure-autoscaling
title: 'Übung: Erstellen einer Skalierungsgruppe aus, und Konfigurieren der automatischen Skalierung'
metadata:
  title: 'Übung: Erstellen einer Skalierungsgruppe aus, und Konfigurieren der automatischen Skalierung'
  description: 'Übung: Erstellen einer Skalierungsgruppe aus, und Konfigurieren der automatischen Skalierung'
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 10
content: |
  [!include[](includes/5-exercise-create-a-scale-set-and-configure-autoscaling.md)]