### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.4-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: Konfigurieren von Anwendungen zum Senden oder Empfangen von Nachrichten über einen Event Hub
metadata:
  title: Konfigurieren von Anwendungen zum Senden oder Empfangen von Nachrichten über einen Event Hub
  description: Konfigurieren von Anwendungen zum Senden oder Empfangen von Nachrichten über einen Event Hub
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 94af9097bf2ee37e91e93d2e51d1d5cc79eb874d
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46343072"
durationInMinutes: 5
content: '[!include[](includes/4-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]'
