### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.4-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: <span data-ttu-id="bcb8c-101">Konfigurieren von Anwendungen zum Senden oder Empfangen von Nachrichten über einen Event Hub</span><span class="sxs-lookup"><span data-stu-id="bcb8c-101">Configure applications to send or receive messages through an Event Hub</span></span>
metadata:
  title: <span data-ttu-id="bcb8c-102">Konfigurieren von Anwendungen zum Senden oder Empfangen von Nachrichten über einen Event Hub</span><span class="sxs-lookup"><span data-stu-id="bcb8c-102">Configure applications to send or receive messages through an Event Hub</span></span>
  description: <span data-ttu-id="bcb8c-103">Konfigurieren von Anwendungen zum Senden oder Empfangen von Nachrichten über einen Event Hub</span><span class="sxs-lookup"><span data-stu-id="bcb8c-103">Configure applications to send or receive messages through an Event Hub</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 94af9097bf2ee37e91e93d2e51d1d5cc79eb874d
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44230720"
durationInMinutes: 5
content: '[!include[](includes/4-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]'
