### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: Configure applications to send or receive messages through an Event Hub
metadata:
  title: Configure applications to send or receive messages through an Event Hub
  description: Configure applications to send or receive messages through an Event Hub
durationInMinutes: 10
content: |
  [!include[](includes/5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]