### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: '<span data-ttu-id="da063-101">Übung: Konfigurieren von Anwendungen zum Senden oder Empfangen von Nachrichten über einen Event Hub</span><span class="sxs-lookup"><span data-stu-id="da063-101">Exercise - Configure applications to send or receive messages through an Event Hub</span></span>'
metadata:
  title: '<span data-ttu-id="da063-102">Übung: Konfigurieren von Anwendungen zum Senden oder Empfangen von Nachrichten über einen Event Hub</span><span class="sxs-lookup"><span data-stu-id="da063-102">Exercise - Configure applications to send or receive messages through an Event Hub</span></span>'
  description: <span data-ttu-id="da063-103">Konfigurieren von Anwendungen zum Senden oder Empfangen von Nachrichten über einen Event Hub</span><span class="sxs-lookup"><span data-stu-id="da063-103">Configure applications to send or receive messages through an Event Hub</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: de40d61e225340c649c9efec1ac10093508b9459
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47125387"
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]'
