### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal
title: Enable and configure Azure VM disk cache by using the Azure portal
metadata:
  title: Enable and configure Azure VM disk cache by using the Azure portal
  description: Enable and configure Azure VM disk cache by using the Azure portal
  ms.date: 09/24/2018
  #TODO: Update with real author name.
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 5
content: |
  [!include[](includes/3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)