### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal
title: <span data-ttu-id="0c858-101">Aktivieren und Konfigurieren des Azure-VM-Datenträgercaches mit dem Azure-Portal</span><span class="sxs-lookup"><span data-stu-id="0c858-101">Enable and configure Azure VM disk cache by using the Azure portal</span></span>
metadata:
  title: <span data-ttu-id="0c858-102">Aktivieren und Konfigurieren des Azure-VM-Datenträgercaches mit dem Azure-Portal</span><span class="sxs-lookup"><span data-stu-id="0c858-102">Enable and configure Azure VM disk cache by using the Azure portal</span></span>
  description: <span data-ttu-id="0c858-103">Aktivieren und Konfigurieren des Azure-VM-Datenträgercaches mit dem Azure-Portal</span><span class="sxs-lookup"><span data-stu-id="0c858-103">Enable and configure Azure VM disk cache by using the Azure portal</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 74553764ab7eed4b5ceed57f9e63596811cdbdc5
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44241175"
durationInMinutes: 5
content: <span data-ttu-id="0c858-104">[!include[](includes/3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)</span><span class="sxs-lookup"><span data-stu-id="0c858-104">[!include[](includes/3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)</span></span>
