### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal
title: <span data-ttu-id="d58c7-101">Aktivieren und Konfigurieren des Azure-VM-Datenträgercaches mit dem Azure-Portal</span><span class="sxs-lookup"><span data-stu-id="d58c7-101">Enable and configure Azure VM disk cache with the Azure portal</span></span>
metadata:
  title: <span data-ttu-id="d58c7-102">Aktivieren und Konfigurieren des Azure-VM-Datenträgercaches mit dem Azure-Portal</span><span class="sxs-lookup"><span data-stu-id="d58c7-102">Enable and configure Azure VM disk cache with the Azure portal</span></span>
  description: <span data-ttu-id="d58c7-103">Aktivieren und Konfigurieren des Azure-VM-Datenträgercaches mit dem Azure-Portal</span><span class="sxs-lookup"><span data-stu-id="d58c7-103">Enable and configure Azure VM disk cache with the Azure portal</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 20238bbb5638ea2e5985a7a51e5885700f64099b
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46343212"
durationInMinutes: 5
content: <span data-ttu-id="d58c7-104">[!include[](includes/3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)</span><span class="sxs-lookup"><span data-stu-id="d58c7-104">[!include[](includes/3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)</span></span>
