### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.5-manage-cache-settings-with-powershell
title: <span data-ttu-id="4a54d-101">Verwalten von Cacheeinstellungen mit PowerShell</span><span class="sxs-lookup"><span data-stu-id="4a54d-101">Manage cache settings with PowerShell</span></span>
metadata:
  title: <span data-ttu-id="4a54d-102">Verwalten von Cacheeinstellungen mit PowerShell</span><span class="sxs-lookup"><span data-stu-id="4a54d-102">Manage cache settings with PowerShell</span></span>
  description: <span data-ttu-id="4a54d-103">Verwalten von Cacheeinstellungen mit PowerShell</span><span class="sxs-lookup"><span data-stu-id="4a54d-103">Manage cache settings with PowerShell</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: b862288f8868319d3a3e0c681632987fbc6419ac
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46338528"
durationInMinutes: 5
content: '[!include[](includes/5-manage-cache-settings-with-powershell.md)]'
