### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.6-exercise-manage-cache-settings-with-powershell
title: Exercise - Manage cache settings with PowerShell
metadata:
  title: Exercise - Manage cache settings with PowerShell
  description: Exercise - Manage cache settings with PowerShell
durationInMinutes: 10
content: |
  [!include[](includes/6-exercise-manage-cache-settings-with-powershell.md)]