### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.1-create-azure-iot-central-application
title: <span data-ttu-id="32607-101">Erstellen einer Azure IoT Central-Anwendung</span><span class="sxs-lookup"><span data-stu-id="32607-101">Create an Azure IoT Central application</span></span>
metadata:
  title: <span data-ttu-id="32607-102">Erstellen einer Azure IoT Central-Anwendung</span><span class="sxs-lookup"><span data-stu-id="32607-102">Create an Azure IoT Central application</span></span>
  description: <span data-ttu-id="32607-103">Erstellen einer Azure IoT Central-Anwendung</span><span class="sxs-lookup"><span data-stu-id="32607-103">Create an Azure IoT Central application</span></span>
  ms.openlocfilehash: e8c698bdbf44cc17d687466702c06b59f7023806
  ms.sourcegitcommit: b97ed72bd7e3fb77b49de71e8ef35d3f70dfd636
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43795671"
durationInMinutes: 12
content: '[!include[](includes/1-create-azure-iot-central-application.md)]'
