### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.3-connect-your-application-to-simulator
title: Verbinden Ihrer Anwendung mit der simulierten Kaffeemaschine
metadata:
  title: Verbinden Ihrer Anwendung mit der simulierten Kaffeemaschine
  description: Verbinden Ihrer Anwendung mit der simulierten Kaffeemaschine
  ms.openlocfilehash: d7dbbf8226940d5a61ee707edd7600b0bfd0bf2e
  ms.sourcegitcommit: b97ed72bd7e3fb77b49de71e8ef35d3f70dfd636
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43794443"
durationInMinutes: 12
content: '[!include[](includes/3-connect-your-application-to-simulator.md)]'
