### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.5-configure-rules-and-actions
title: <span data-ttu-id="7f7bb-101">Konfigurieren von Regeln und Aktionen zum Überwachen Ihrer Kaffeemaschine</span><span class="sxs-lookup"><span data-stu-id="7f7bb-101">Configure rules and actions to monitor your coffee machine</span></span>
metadata:
  title: <span data-ttu-id="7f7bb-102">Konfigurieren von Regeln und Aktionen zum Überwachen Ihrer Kaffeemaschine</span><span class="sxs-lookup"><span data-stu-id="7f7bb-102">Configure rules and actions to monitor your coffee machine</span></span>
  description: <span data-ttu-id="7f7bb-103">Konfigurieren von Regeln und Aktionen zum Überwachen Ihrer Kaffeemaschine</span><span class="sxs-lookup"><span data-stu-id="7f7bb-103">Configure rules and actions to monitor your coffee machine</span></span>
  ms.openlocfilehash: b88da62e3fbf019371ec59a009d2a52e3ced1b75
  ms.sourcegitcommit: b97ed72bd7e3fb77b49de71e8ef35d3f70dfd636
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43795728"
durationInMinutes: 12
content: '[!include[](includes/5-configure-rules-and-actions.md)]'
