### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.10-exercise-connect-with-your-azure-storage-configuration
title: Connect with your Azure Storage configuration
metadata:
  title: Connect with your Azure Storage configuration
  description: Connect with your Azure Storage configuration
  zone_pivot_groups: dev-lang-csharp-javascript
interactive: bash-editor
durationInMinutes: 15
content: |
  [!include[](includes/10-exercise-connect-with-your-azure-storage-configuration.md)]