### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.10-exercise-connect-with-your-azure-storage-configuration
title: <span data-ttu-id="08a29-101">Herstellen einer Verbindung mit Ihrer Azure Storage-Konfiguration</span><span class="sxs-lookup"><span data-stu-id="08a29-101">Connect with your Azure Storage configuration</span></span>
metadata:
  title: <span data-ttu-id="08a29-102">Herstellen einer Verbindung mit Ihrer Azure Storage-Konfiguration</span><span class="sxs-lookup"><span data-stu-id="08a29-102">Connect with your Azure Storage configuration</span></span>
  description: <span data-ttu-id="08a29-103">Herstellen einer Verbindung mit Ihrer Azure Storage-Konfiguration</span><span class="sxs-lookup"><span data-stu-id="08a29-103">Connect with your Azure Storage configuration</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  zone_pivot_groups: dev-lang-csharp-javascript
  ms.openlocfilehash: 744fed3cd3989012c289c6255818479a6f1f7d2b
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47124763"
interactive: bash-editor
azureSandbox: true
durationInMinutes: 15
content: '[!include[](includes/10-exercise-connect-with-your-azure-storage-configuration.md)]'
