### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.10-exercise-connect-with-your-azure-storage-configuration
title: <span data-ttu-id="33904-101">Herstellen einer Verbindung mit Ihrer Azure Storage-Konfiguration</span><span class="sxs-lookup"><span data-stu-id="33904-101">Connect with your Azure Storage configuration</span></span>
metadata:
  title: <span data-ttu-id="33904-102">Herstellen einer Verbindung mit Ihrer Azure Storage-Konfiguration</span><span class="sxs-lookup"><span data-stu-id="33904-102">Connect with your Azure Storage configuration</span></span>
  description: <span data-ttu-id="33904-103">Herstellen einer Verbindung mit Ihrer Azure Storage-Konfiguration</span><span class="sxs-lookup"><span data-stu-id="33904-103">Connect with your Azure Storage configuration</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  zone_pivot_groups: dev-lang-csharp-javascript
  ms.openlocfilehash: fc60b9e975dbd76fa90a087eeb19494805683edf
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44239322"
interactive: bash-editor
durationInMinutes: 15
content: '[!include[](includes/10-exercise-connect-with-your-azure-storage-configuration.md)]'
