### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.7-exercise-add-azure-storage-configuration-to-your-app
title: <span data-ttu-id="5189d-101">Hinzufügen einer Azure Storage-Konfiguration zur App</span><span class="sxs-lookup"><span data-stu-id="5189d-101">Add Azure Storage configuration to your app</span></span>
metadata:
  title: <span data-ttu-id="5189d-102">Hinzufügen einer Azure Storage-Konfiguration zur App</span><span class="sxs-lookup"><span data-stu-id="5189d-102">Add Azure Storage configuration to your app</span></span>
  description: <span data-ttu-id="5189d-103">Hinzufügen einer Azure Storage-Konfiguration zur App</span><span class="sxs-lookup"><span data-stu-id="5189d-103">Add Azure Storage configuration to your app</span></span>
  ms.openlocfilehash: e152336211d9a6d9e37f9443e94712e5afac3722
  ms.sourcegitcommit: e90461bc6f88bca3b53183b476553633f93990a3
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "44043286"
durationInMinutes: 10
content: '[!include[](includes/7-exercise-add-azure-storage-configuration-to-your-app.md)]'
