### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.7-exercise-add-azure-storage-configuration-to-your-app
title: <span data-ttu-id="78059-101">Hinzufügen einer Azure Storage-Konfiguration zur App</span><span class="sxs-lookup"><span data-stu-id="78059-101">Add Azure Storage configuration to your app</span></span>
metadata:
  title: <span data-ttu-id="78059-102">Hinzufügen einer Azure Storage-Konfiguration zur App</span><span class="sxs-lookup"><span data-stu-id="78059-102">Add Azure Storage configuration to your app</span></span>
  description: <span data-ttu-id="78059-103">Hinzufügen einer Azure Storage-Konfiguration zur App</span><span class="sxs-lookup"><span data-stu-id="78059-103">Add Azure Storage configuration to your app</span></span>
  ms.openlocfilehash: fe194feea9e7ecd5018060b7451b9fa0b8bfba1f
  ms.sourcegitcommit: b97ed72bd7e3fb77b49de71e8ef35d3f70dfd636
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43792204"
durationInMinutes: 10
content: '[!include[](includes/7-exercise-add-azure-storage-configuration-to-your-app.md)]'
