### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.8-exercise-add-azure-storage-configuration-to-your-app
title: Add Azure Storage configuration to your app
metadata:
  title: Add Azure Storage configuration to your app
  description: Add Azure Storage configuration to your app
  zone_pivot_groups: dev-lang-csharp-javascript
interactive: bash-editor
durationInMinutes: 10
content: |
  [!include[](includes/8-exercise-add-azure-storage-configuration-to-your-app.md)]