### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.9-exercise-connect-with-your-azure-storage-configuration
title: <span data-ttu-id="6c4fa-101">Herstellen einer Verbindung mit Ihrer Azure Storage-Konfiguration</span><span class="sxs-lookup"><span data-stu-id="6c4fa-101">Connect with your Azure Storage configuration</span></span>
metadata:
  title: <span data-ttu-id="6c4fa-102">Herstellen einer Verbindung mit Ihrer Azure Storage-Konfiguration</span><span class="sxs-lookup"><span data-stu-id="6c4fa-102">Connect with your Azure Storage configuration</span></span>
  description: <span data-ttu-id="6c4fa-103">Herstellen einer Verbindung mit Ihrer Azure Storage-Konfiguration</span><span class="sxs-lookup"><span data-stu-id="6c4fa-103">Connect with your Azure Storage configuration</span></span>
  ms.openlocfilehash: d751f669ef3861a64abfdd02301aa7e79edb9c12
  ms.sourcegitcommit: e90461bc6f88bca3b53183b476553633f93990a3
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "44043779"
durationInMinutes: 10
content: '[!include[](includes/9-exercise-connect-with-your-azure-storage-configuration.md)]'
