### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.9-exercise-connect-with-your-azure-storage-configuration
title: Herstellen einer Verbindung mit Ihrer Azure Storage-Konfiguration
metadata:
  title: Herstellen einer Verbindung mit Ihrer Azure Storage-Konfiguration
  description: Herstellen einer Verbindung mit Ihrer Azure Storage-Konfiguration
  ms.openlocfilehash: d751f669ef3861a64abfdd02301aa7e79edb9c12
  ms.sourcegitcommit: e90461bc6f88bca3b53183b476553633f93990a3
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "44043779"
durationInMinutes: 10
content: '[!include[](includes/9-exercise-connect-with-your-azure-storage-configuration.md)]'
