### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.9-exercise-connect-with-your-azure-storage-configuration
title: <span data-ttu-id="758d0-101">Herstellen einer Verbindung mit Ihrer Azure Storage-Konfiguration</span><span class="sxs-lookup"><span data-stu-id="758d0-101">Connect with your Azure Storage configuration</span></span>
metadata:
  title: <span data-ttu-id="758d0-102">Herstellen einer Verbindung mit Ihrer Azure Storage-Konfiguration</span><span class="sxs-lookup"><span data-stu-id="758d0-102">Connect with your Azure Storage configuration</span></span>
  description: <span data-ttu-id="758d0-103">Herstellen einer Verbindung mit Ihrer Azure Storage-Konfiguration</span><span class="sxs-lookup"><span data-stu-id="758d0-103">Connect with your Azure Storage configuration</span></span>
  ms.openlocfilehash: d7b2a71726a5830927bb64e8d4008c9f9df291f4
  ms.sourcegitcommit: b97ed72bd7e3fb77b49de71e8ef35d3f70dfd636
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43792748"
durationInMinutes: 10
content: '[!include[](includes/9-exercise-connect-with-your-azure-storage-configuration.md)]'
