### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.9-exercise-connect-with-your-azure-storage-configuration
title: 'Übung: Herstellen einer Verbindung mit der Azure Storage-Konfiguration'
metadata:
  title: 'Übung: Herstellen einer Verbindung mit der Azure Storage-Konfiguration'
  description: 'Übung: Herstellen einer Verbindung mit der Azure Storage-Konfiguration'
  ms.openlocfilehash: d712e34b220d3ebb9847cb907fb512fb4de7da0b
  ms.sourcegitcommit: 107578417899e44b5611917dec7bcc21d4c1582e
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43229243"
durationInMinutes: 10
content: '[!include[](includes/9-exercise-connect-with-your-azure-storage-configuration.md)]'
