### YamlMime:ModuleUnit
uid: learn.manage-secrets-with-azure-key-vault.5-configure-deploy-run-azure
title: <span data-ttu-id="6e544-101">Konfigurieren, bereitstellen und Ausführen in Azure</span><span class="sxs-lookup"><span data-stu-id="6e544-101">Configure, deploy and run in Azure</span></span>
metadata:
  title: <span data-ttu-id="6e544-102">Konfigurieren, bereitstellen und Ausführen in Azure</span><span class="sxs-lookup"><span data-stu-id="6e544-102">Configure, deploy and run in Azure</span></span>
  description: <span data-ttu-id="6e544-103">Konfigurieren, bereitstellen und Ausführen in Azure</span><span class="sxs-lookup"><span data-stu-id="6e544-103">Configure, deploy and run in Azure</span></span>
  ms.openlocfilehash: b8341db5fd65953073b2bac5976a1ac569549bb3
  ms.sourcegitcommit: 1a80693c9c86d6246bf80d6b703fe846bb61dbfe
  ms.translationtype: MT
  ms.contentlocale: de-DE
  ms.lasthandoff: 08/17/2018
  ms.locfileid: "40184647"
durationInMinutes: 10
interactive: bash
content: '[!include[](includes/5-configure-deploy-run-azure.md)]'
