### YamlMime:ModuleUnit
uid: learn.manage-secrets-with-azure-key-vault.6-configure-deploy-run-azure
title: <span data-ttu-id="1fc0a-101">Konfigurieren, Bereitstellen und Ausführen in Azure</span><span class="sxs-lookup"><span data-stu-id="1fc0a-101">Configure, deploy, and run in Azure</span></span>
metadata:
  title: <span data-ttu-id="1fc0a-102">Konfigurieren, Bereitstellen und Ausführen in Azure</span><span class="sxs-lookup"><span data-stu-id="1fc0a-102">Configure, deploy, and run in Azure</span></span>
  description: <span data-ttu-id="1fc0a-103">Konfigurieren, Bereitstellen und Ausführen in Azure</span><span class="sxs-lookup"><span data-stu-id="1fc0a-103">Configure, deploy, and run in Azure</span></span>
  ms.openlocfilehash: 2877e343b38fce7016c15621f390db6343838e7d
  ms.sourcegitcommit: 12b4711682dac42f742a944fd9baa0e9dd09cf35
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 08/22/2018
  ms.locfileid: "40447481"
durationInMinutes: 10
interactive: bash
content: '[!include[](includes/6-configure-deploy-run-azure.md)]'
