### YamlMime:ModuleUnit
uid: learn.manage-secrets-with-azure-key-vault.6-configure-deploy-run-azure
title: Configure, deploy, and run in Azure
metadata:
  title: Configure, deploy, and run in Azure
  description: Configure, deploy, and run in Azure
  ms.date: 09/24/2018
  #TODO: Update with real author name.
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 12
interactive: bash
azureSandbox: true
content: |
  [!include[](includes/6-configure-deploy-run-azure.md)]