### YamlMime:ModuleUnit
uid: learn.intro-to-containers.2-configure-local
metadata:
  title: <span data-ttu-id="806e5-101">Konfigurieren einer lokalen Containerentwicklungsumgebung</span><span class="sxs-lookup"><span data-stu-id="806e5-101">Configure a local container development environment</span></span>
  description: <span data-ttu-id="806e5-102">Konfigurieren Sie eine lokale Containerentwicklungsumgebung.</span><span class="sxs-lookup"><span data-stu-id="806e5-102">Configure a local container development environment.</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 365b86322b9585abcedd1a61fdcf91840bae48bf
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44246717"
title: <span data-ttu-id="806e5-103">Konfigurieren einer lokalen Containerentwicklungsumgebung</span><span class="sxs-lookup"><span data-stu-id="806e5-103">Configure a local container development environment</span></span>
durationInMinutes: 10
content: '[!include[](includes/2-configure-local.md)]'
