### YamlMime:ModuleUnit
uid: learn.intro-to-containers.2-configure-local
metadata:
  title: <span data-ttu-id="783a3-101">Konfigurieren einer lokalen Containerentwicklungsumgebung</span><span class="sxs-lookup"><span data-stu-id="783a3-101">Configure a local container development environment</span></span>
  description: <span data-ttu-id="783a3-102">Konfigurieren Sie eine lokale Containerentwicklungsumgebung.</span><span class="sxs-lookup"><span data-stu-id="783a3-102">Configure a local container development environment.</span></span>
  displayType: one-column
  ms.openlocfilehash: 943d4a5d8cb84c7b07d1e8ae49dac8636763f797
  ms.sourcegitcommit: 16445658b8c25e5f5cbcfc7b1d8a36222f4e902c
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 08/24/2018
  ms.locfileid: "42907565"
title: <span data-ttu-id="783a3-103">Konfigurieren einer lokalen Containerentwicklungsumgebung</span><span class="sxs-lookup"><span data-stu-id="783a3-103">Configure a local container development environment</span></span>
durationInMinutes: 10
content: '[!include[](includes/2-configure-local.md)]'
