### YamlMime:ModuleUnit
uid: learn.intro-to-containers.2-configure-local
metadata:
  title: Konfigurieren einer lokalen Containerentwicklungsumgebung
  description: Konfigurieren Sie eine lokale Containerentwicklungsumgebung.
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
title: Konfigurieren einer lokalen Containerentwicklungsumgebung
durationInMinutes: 10
content: |
  [!include[](includes/2-configure-local.md)]