### YamlMime:ModuleUnit
uid: learn.intro-to-containers.2-configure-local
metadata:
  title: Konfigurieren einer lokalen Containerentwicklungsumgebung
  description: Konfigurieren Sie eine lokale Containerentwicklungsumgebung.
  ms.openlocfilehash: f33047eb1295ea2dd44904a8e2ddb1d78b413682
  ms.sourcegitcommit: 56db32ad6f98b7d769f2b1201825d4f6d9b7362d
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43727902"
title: Konfigurieren einer lokalen Containerentwicklungsumgebung
durationInMinutes: 10
content: '[!include[](includes/2-configure-local.md)]'
