### YamlMime:ModuleUnit
uid: learn.design-for-performance-and-scalability.5-identify-performance-bottlenecks-in-your-application
title: Erkennen von Leistungsengpässen in Ihrer Anwendung
metadata:
  title: Erkennen von Leistungsengpässen in Ihrer Anwendung
  description: In dieser Einheit wird erörtert, wie Sie Leistungsengpässe in Ihrer Anwendung erkennen.
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: c7d8f1f8564a139f58fb17efc300af92e96cf906
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46339821"
durationInMinutes: 9
content: >
  [!include[](includes/5-identify-performance-bottlenecks-in-your-application.md)]
quiz:
  title: Überprüfen Sie Ihre Kenntnisse
  questions:
  - content: Welche der folgenden Aussagen beschreibt Application Insights am besten?
    choices:
    - content: Eine einzelne Ansicht für alle Ihre Überwachungsanforderungen in Azure
      isCorrect: false
      incorrectExplanation: Obwohl Application Insights eine große Menge Daten für die Leistung Ihrer Anwendung bereitstellen kann, ist es keine umfassende Azure-Überwachungslösung.
    - content: Implementierung der Überwachungsmuster für den Integritätsendpunkt
      isCorrect: false
      incorrectExplanation: Das Überwachungsmuster für den Integritätsendpunkt konzentriert sich auf die Endpunkte, die von der Anwendung für die allgemeine Integrität verfügbar gemacht werden.
    - content: Arbeitsbereich, in dem die Sammlung von Protokollen in der gesamten Infrastruktur und Anwendungen übergreifend aktiviert wird
      isCorrect: false
      incorrectExplanation: Log Analytics ist ein Arbeitsbereich, in dem die Sammlung von Protokollen in der gesamten Infrastruktur und Anwendungen übergreifend aktiviert wird.
    - content: Dienst zum Überwachen von Verfügbarkeit, Leistung und Nutzung von Webanwendungen
      isCorrect: true
      correctExplanation: Application Insights ist ein Dienst zum Überwachen von Verfügbarkeit, Leistung und Nutzung von Webanwendungen.
  - content: 'Wahr oder falsch: Sie können Log Analytics verwenden, um benutzerdefinierte Protokolle und Metriken nachzuverfolgen.'
    choices:
    - content: Wahr
      isCorrect: true
      correctExplanation: Für benutzerdefinierte Protokolle und Metriken können Sie die HTTP-Datensammlungs-API verwenden, um Daten eines beliebigen REST-API-Clients in Log Analytics zu schreiben, oder eine Azure-Logik-App, um Daten aus einem benutzerdefinierten Workflow zu schreiben.
    - content: Falsch
      isCorrect: false
      incorrectExplanation: Für benutzerdefinierte Protokolle und Metriken können Sie die HTTP-Datensammlungs-API verwenden, um Daten eines beliebigen REST-API-Clients in Log Analytics zu schreiben, oder eine Azure-Logik-App, um Daten aus einem benutzerdefinierten Workflow zu schreiben.
