### YamlMime:ModuleUnit
uid: learn.design-for-performance-and-scalability.5-identify-performance-bottlenecks-in-your-application
title: Erkennen von Leistungsengpässen in Ihrer Anwendung
metadata:
  title: Erkennen von Leistungsengpässen in Ihrer Anwendung
  description: 'In dieser Einheit wird erörtert, wie Sie Leistungsengpässe in Ihrer Anwendung erkennen.'
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 5
content: |
  [!include[](includes/5-identify-performance-bottlenecks-in-your-application.md)]
quiz:
  title: 'Wissenstest: Erkennen von Leistungsengpässen in Ihrer Anwendung'
  questions:
    - content: Welche der folgenden Aussagen beschreibt Application Insights am besten?
      choices:
        - content: Einzelne Verwaltungskonsole für Überwachungsanforderungen in Azure
          isCorrect: false
          incorrectExplanation: 'Obwohl Application Insights eine große Menge Daten für die Leistung Ihrer Anwendung bereitstellen kann, ist es keine umfassende Azure-Überwachungslösung.'
        - content: Eine Implementierung der Überwachungsmuster für den Integritätsendpunkt
          isCorrect: false
          incorrectExplanation: 'Das Überwachungsmuster für den Integritätsendpunkt konzentriert sich auf die Endpunkte, die von der Anwendung für die allgemeine Integrität verfügbar gemacht werden.'
        - content: 'Arbeitsbereich, in dem die Sammlung von Protokollen in der gesamten Infrastruktur und Anwendungen aktiviert wird'
          isCorrect: false
          incorrectExplanation: 'Log Analytics ist ein Arbeitsbereich, in dem die Sammlung von Protokollen in der gesamten Infrastruktur und Anwendungen aktiviert wird.'
        - content: 'Dienst zum Überwachen von Verfügbarkeit, Leistung und Nutzung von Webanwendungen'
          isCorrect: true
          correctExplanation: 'Application Insights ist ein Dienst zum Überwachen von Verfügbarkeit, Leistung und Nutzung von Webanwendungen.'
    - content: 'Sie können Log Analytics verwenden, um benutzerdefinierte Protokolle und Metriken nachzuverfolgen.'
      choices:
        - content: Richtig
          isCorrect: true
          correctExplanation: 'Für benutzerdefinierte Protokolle und Metriken können Sie die HTTP-Datensammlungs-API verwenden, um Daten eines beliebigen REST-API-Clients in Log Analytics zu schreiben, oder eine Azure-Logik-App, um Daten aus einem benutzerdefinierten Workflow zu schreiben.'
        - content: Falsch
          isCorrect: false
          incorrectExplanation: 'Für benutzerdefinierte Protokolle und Metriken können Sie die HTTP-Datensammlungs-API verwenden, um Daten eines beliebigen REST-API-Clients in Log Analytics zu schreiben, oder eine Azure-Logik-App, um Daten aus einem benutzerdefinierten Workflow zu schreiben.'