### YamlMime:ModuleUnit
uid: learn.introduction-to-security.5-network-security
title: Schützen Ihres Netzwerks
metadata:
  title: Schützen Ihres Netzwerks
  description: In dieser Einheit wird erörtert, wie Sie Ihre Netzwerkinfrastruktur schützen.
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 434584c1861f5b8031069c787b878c654a8ba848
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47129470"
durationInMinutes: 5
content: '[!include[](includes/5-network-security.md)]'
