### YamlMime:ModuleUnit
uid: learn.introduction-to-security.5-network-security
title: Schützen Sie Ihr Netzwerk
metadata:
  title: Schützen Sie Ihr Netzwerk
  description: 'In dieser Einheit erörtern wir, wie Sie Ihre Netzwerkinfrastruktur zu schützen.'
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 5
content: |
  [!include[](includes/5-network-security.md)]