### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: Übung – Erstellen einer ASP.NET Core-Anwendung unter Linux
metadata:
  title: Übung – Erstellen einer ASP.NET Core-Anwendung unter Linux
  description: Übung – Erstellen einer ASP.NET Core-Anwendung unter Linux
  ms.openlocfilehash: 1205619f0129555a08587fa142627e6d917e3fcb
  ms.sourcegitcommit: 7cb102aab9e02ef52429d61a119a574c7ad3b2fb
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43725510"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
