### YamlMime:ModuleUnit
uid: learn.interactive-deep-learning.4-configure-dsvm
title: Konfigurieren einer DSVM
metadata:
  title: Konfigurieren der Data Science Virtual Machine für Deep Learning
  description: Konfigurieren der Data Science Virtual Machine für Deep Learning
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
labId: 45998
interactive: bash
azureSandbox: true
durationInMinutes: 30
content: |
  [!include[](includes/4-configure-dsvm.md)]