### YamlMime:ModuleUnit
uid: learn.interactive-deep-learning.4-configure-dsvm
title: <span data-ttu-id="0d3a2-101">Konfigurieren einer DSVM</span><span class="sxs-lookup"><span data-stu-id="0d3a2-101">Configure DSVM</span></span>
metadata:
  title: <span data-ttu-id="0d3a2-102">Konfigurieren der Data Science Virtual Machine für Deep Learning</span><span class="sxs-lookup"><span data-stu-id="0d3a2-102">Configure the Data Science Virtual Machine for Deep Learning</span></span>
  description: <span data-ttu-id="0d3a2-103">Konfigurieren der Data Science Virtual Machine für Deep Learning</span><span class="sxs-lookup"><span data-stu-id="0d3a2-103">Configure the Data Science Virtual Machine for Deep Learning</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: e7beee6bf1a56df0378cba82b042d506589f361d
  ms.sourcegitcommit: 8213d1af6ad9da967a5e195f0b40b00265cb192c
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/10/2018
  ms.locfileid: "44309336"
interactive: bash
azureSandbox: true
durationInMinutes: 30
content: '[!include[](includes/4-configure-dsvm.md)]'
