### YamlMime:ModuleUnit
uid: learn.optimize-web-app-with-redis.3-configure-redis-cache
title: Konfigurieren von Redis Cache
metadata:
  title: Konfigurieren von Redis Cache
  description: Konfigurieren von Redis Cache
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: cf34eb91055b1a3f200c204af82bc93cb86e156f
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45760538"
durationInMinutes: 5
content: '[!include[](includes/3-configure-redis-cache.md)]'
