### YamlMime:ModuleUnit
uid: learn.optimize-web-app-with-redis.3-configure-redis-cache
title: Konfigurieren von Redis Cache
metadata:
  title: Konfigurieren von Redis Cache
  description: Konfigurieren von Redis Cache
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: cf34eb91055b1a3f200c204af82bc93cb86e156f
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47137598"
durationInMinutes: 5
content: '[!include[](includes/3-configure-redis-cache.md)]'
