### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
metadata:
  title: Festlegen von Umgebungsvariablen
  description: Legen Sie Umgebungsvariablen in Azure Container Instances fest.
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
title: Festlegen von Umgebungsvariablen
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: |
  [!include[](includes/4-use-environment-variables.md)]