### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
metadata:
  title: <span data-ttu-id="f2b42-101">Festlegen von Umgebungsvariablen</span><span class="sxs-lookup"><span data-stu-id="f2b42-101">Set environment variables</span></span>
  description: <span data-ttu-id="f2b42-102">Legen Sie Umgebungsvariablen in Azure Container Instances fest.</span><span class="sxs-lookup"><span data-stu-id="f2b42-102">Set environment variables in Azure Container Instances.</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 121d22c224c33875cf10038d9c63596882a3b1f4
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47139319"
title: <span data-ttu-id="f2b42-103">Festlegen von Umgebungsvariablen</span><span class="sxs-lookup"><span data-stu-id="f2b42-103">Set environment variables</span></span>
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/4-use-environment-variables.md)]'
