### YamlMime:ModuleUnit
uid: learn.secure-your-azure-virtual-machine-disks.6-exercise-automate-secure-vm-deployments-using-arm-templates
title: 'Übung: Automatisieren der sicheren VM-Bereitstellung mithilfe der Verschlüsselung mit Azure Resource Manager-Vorlagen'
metadata:
  title: 'Übung: Automatisieren der sicheren VM-Bereitstellung mithilfe der Verschlüsselung mit Azure Resource Manager-Vorlagen'
  description: 'Übung: Automatisieren der sicheren VM-Bereitstellung mithilfe der Verschlüsselung mit Azure Resource Manager-Vorlagen'
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
azureSandbox: true
durationInMinutes: 10
content: |
  [!include[](includes/6-exercise-automate-secure-vm-deployments-using-arm-templates.md)]