### YamlMime:ModuleUnit
uid: learn.design-for-security.6-network-security
title: Netzwerksicherheit
metadata:
  title: Netzwerksicherheit
  description: In dieser Einheit wird erörtert, wie Sie Ihre Netzwerkinfrastruktur schützen.
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 90be1e461ce19e0bd7a18e869397db2d0ab3abfa
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44240752"
durationInMinutes: 5
content: >
  [!include[](includes/6-network-security.md)]
quiz:
  title: 'Wissenstest: Netzwerksicherheit'
  questions:
  - content: Welche der folgenden Übertragungen können mit Azure-NSGs abgesichert werden?
    choices:
    - content: Übertragungen zwischen virtuellen Computern und dem Internet
      isCorrect: false
      incorrectExplanation: Mit NSGs kann diese Übertragung zwar abgesichert werden, doch dies ist nicht die einzige richtige Antwortmöglichkeit.
    - content: Übertragungen zwischen virtuellen Computern innerhalb eines VNET
      isCorrect: false
      incorrectExplanation: Mit NSGs kann diese Übertragung zwar abgesichert werden, doch dies ist nicht die einzige richtige Antwortmöglichkeit.
    - content: Übertragungen zwischen Systemen in einem lokalen Netzwerk
      isCorrect: false
      incorrectExplanation: Mit NSGs kann diese Übertragung zwar abgesichert werden, doch dies ist nicht die einzige richtige Antwortmöglichkeit.
    - content: Alle oben genannten Möglichkeiten sind zutreffend.
      isCorrect: true
      correctExplanation: Mit NSGs können alle der oben genannten Übertragungen abgesichert werden.
  - content: Welche der folgenden ist keine Methode zum Schutz von Diensten mit Internetzugriff vor Netzwerkangriffen?
    choices:
    - content: Azure DDoS
      isCorrect: false
      incorrectExplanation: 'Mit Azure DDoS können mit dem Internet verbundene Dienste vor einem DoS-Angriff geschützt werden. '
    - content: Azure Application Gateway-WAF
      isCorrect: false
      incorrectExplanation: Mit Application Gateway-WAF können mit dem Internet verbundene Dienste vor XSS-Angriffen und Einschleusung von SQL-Befehlen geschützt werden.
    - content: Azure Disk Encryption
      isCorrect: true
      correctExplanation: Mit Azure Disk Encryption werden die VHDs eines virtuellen Computers geschützt, falls diese ohne Berechtigung zugänglich gemacht werden. Der Dienst bietet aber keinen Schutz vor Netzwerkangriffen.
    - content: Virtuelles Netzwerkgerät
      isCorrect: false
      incorrectExplanation: Virtuelle Netzwerkgeräte stellen anpassbaren Netzwerkzugriffsschutz für Ressourcen bereit, die mit dem Internet verbunden sind.
