### YamlMime:ModuleUnit
uid: learn.design-for-security.6-network-security
title: Netzwerksicherheit
metadata:
  title: Netzwerksicherheit
  description: In dieser Einheit wird erörtert, wie Sie Ihre Netzwerkinfrastruktur schützen.
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 9cd7f21680ad44848f6cf4240c1ae3289839ad2d
  ms.sourcegitcommit: 04cba4eb84188dd50349e0efcf90629aadb7b397
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 10/04/2018
  ms.locfileid: "48786713"
durationInMinutes: 10
content: >
  [!include[](includes/6-network-security.md)]
quiz:
  title: Überprüfen Sie Ihr Wissen
  questions:
  - content: Welche der folgenden Arten der Kommunikation können mit Azure-Netzwerksicherheitsgruppen abgesichert werden?
    choices:
    - content: Kommunikation zwischen Azure-VMs und dem Internet
      isCorrect: false
      incorrectExplanation: Mit Netzwerksicherheitsgruppen kann diese Kommunikation zwar abgesichert werden, doch dies ist nicht die einzige richtige Antwortmöglichkeit.
    - content: Kommunikation zwischen Azure-VMs innerhalb eines VNet
      isCorrect: false
      incorrectExplanation: Mit Netzwerksicherheitsgruppen kann diese Kommunikation zwar abgesichert werden, doch dies ist nicht die einzige richtige Antwortmöglichkeit.
    - content: Kommunikation zwischen Azure-VMs und Systemen in einem lokalen Netzwerk
      isCorrect: false
      incorrectExplanation: Mit Netzwerksicherheitsgruppen kann diese Kommunikation zwar abgesichert werden, doch dies ist nicht die einzige richtige Antwortmöglichkeit.
    - content: Alle oben genannten Möglichkeiten sind zutreffend.
      isCorrect: true
      correctExplanation: Netzwerksicherheitsgruppen sind vollständig anpassbar und bieten Ihnen die Möglichkeit, die Netzwerkkommunikation zu und von Ihren VMs vollständig zu sperren.
  - content: Welche der folgenden möglichen Antworten ist keine Methode zum Schutz von Diensten mit Internetzugriff vor Netzwerkangriffen?
    choices:
    - content: Azure DDoS
      isCorrect: false
      incorrectExplanation: 'Mit Azure DDoS können mit dem Internet verbundene Dienste vor einem DoS-Angriff geschützt werden. '
    - content: Azure Application Gateway-WAF
      isCorrect: false
      incorrectExplanation: Mit Application Gateway-WAF können mit dem Internet verbundene Dienste vor XSS-Angriffen und Einschleusung von SQL-Befehlen geschützt werden.
    - content: Azure Disk Encryption
      isCorrect: true
      correctExplanation: Mit Azure Disk Encryption werden die VHDs eines virtuellen Computers geschützt, falls diese ohne Berechtigung zugänglich gemacht werden. Der Dienst bietet aber keinen Schutz vor Netzwerkangriffen.
    - content: Virtuelles Netzwerkgerät
      isCorrect: false
      incorrectExplanation: Virtuelle Netzwerkgeräte stellen anpassbaren Netzwerkzugriffsschutz für Ressourcen bereit, die mit dem Internet verbunden sind.
