### YamlMime:ModuleUnit
uid: learn.design-for-security.6-network-security
title: Netzwerksicherheit
metadata:
  title: Netzwerksicherheit
  description: In dieser Einheit wird erörtert, wie Sie Ihre Netzwerkinfrastruktur schützen.
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: cc35a096e064136f7d56fc05c4ce856fd1918641
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46343007"
durationInMinutes: 10
content: >
  [!include[](includes/6-network-security.md)]
quiz:
  title: Überprüfen Sie Ihre Kenntnisse
  questions:
  - content: Welche der folgenden Übertragungen können mit Azure-Netzwerksicherheitsgruppen abgesichert werden?
    choices:
    - content: VMs und das Internet
      isCorrect: false
      incorrectExplanation: Netzwerksicherheitsgruppen sind vollständig anpassbar und bieten Ihnen die Möglichkeit, die Netzwerkkommunikation zu und von Ihren VMs vollständig zu sperren.
    - content: Virtuelle Computer in einem VNET
      isCorrect: false
      incorrectExplanation: Netzwerksicherheitsgruppen sind vollständig anpassbar und bieten Ihnen die Möglichkeit, die Netzwerkkommunikation zu und von Ihren VMs vollständig zu sperren.
    - content: Systeme in einem lokalen Netzwerk
      isCorrect: false
      incorrectExplanation: Netzwerksicherheitsgruppen sind vollständig anpassbar und bieten Ihnen die Möglichkeit, die Netzwerkkommunikation zu und von Ihren VMs vollständig zu sperren.
    - content: Alle oben genannten Möglichkeiten sind zutreffend.
      isCorrect: true
      correctExplanation: Netzwerksicherheitsgruppen sind vollständig anpassbar und bieten Ihnen die Möglichkeit, die Netzwerkkommunikation zu und von Ihren VMs vollständig zu sperren.
  - content: Welche der folgenden möglichen Antworten ist keine Methode zum Schutz von Diensten mit Internetzugriff vor Netzwerkangriffen?
    choices:
    - content: Azure DDoS
      isCorrect: false
      incorrectExplanation: Mit Azure Disk Encryption werden die virtuellen Festplatten eines virtuellen Computers geschützt, falls diese ohne Berechtigung zugänglich gemacht werden. Der Dienst bietet aber keinen Schutz vor Netzwerkangriffen.
    - content: Azure Application Gateway-WAF
      isCorrect: false
      incorrectExplanation: Mit Azure Disk Encryption werden die virtuellen Festplatten eines virtuellen Computers geschützt, falls diese ohne Berechtigung zugänglich gemacht werden. Der Dienst bietet aber keinen Schutz vor Netzwerkangriffen.
    - content: Azure Disk Encryption
      isCorrect: true
      correctExplanation: Mit Azure Disk Encryption werden die virtuellen Festplatten eines virtuellen Computers geschützt, falls diese ohne Berechtigung zugänglich gemacht werden. Der Dienst bietet aber keinen Schutz vor Netzwerkangriffen.
    - content: Virtuelles Netzwerkgerät
      isCorrect: false
      incorrectExplanation: Mit Azure Disk Encryption werden die virtuellen Festplatten eines virtuellen Computers geschützt, falls diese ohne Berechtigung zugänglich gemacht werden. Der Dienst bietet aber keinen Schutz vor Netzwerkangriffen.
