### YamlMime:ModuleUnit
uid: learn.design-for-security.6-network-security
title: Netzwerksicherheit
metadata:
  title: Netzwerksicherheit
  description: 'In dieser Einheit wird erörtert, wie Sie Ihre Netzwerkinfrastruktur schützen.'
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 5
content: |
  [!include[](includes/6-network-security.md)]
quiz:
  title: 'Wissenstest: Netzwerksicherheit'
  questions:
    - content: Azure-NSGs können zum Sichern der Kommunikation zwischen welche der folgenden verwendet werden?
      choices:
        - content: Kommunikation zwischen virtuellen Computern und dem internet
          isCorrect: false
          incorrectExplanation: 'NSGs können verwendet werden, um diesen Flow Kommunikation zu sichern, aber dies ist nicht die nur die richtige Wahl.'
        - content: Kommunikation zwischen virtuellen Computern in einem VNet
          isCorrect: false
          incorrectExplanation: 'NSGs können verwendet werden, um diesen Flow Kommunikation zu sichern, aber dies ist nicht die nur die richtige Wahl.'
        - content: Kommunikation mit Systemen in einem lokalen Netzwerk
          isCorrect: false
          incorrectExplanation: 'NSGs können verwendet werden, um diesen Flow Kommunikation zu sichern, aber dies ist nicht die nur die richtige Wahl.'
        - content: Alle oben genannten Möglichkeiten
          isCorrect: true
          correctExplanation: 'NSGs können verwendet werden, um alle der oben genannten Kommunikationsflüsse zu sichern.'
    - content: Welche der folgenden ist keine Methode zum Schutz von Diensten mit Internetzugriff vor Netzwerkangriffen?
      choices:
        - content: Azure DDoS
          isCorrect: false
          incorrectExplanation: 'Azure DDoS kann verwendet werden, um dem Internet verbundenen Dienste von einem DoS-Angriff zu schützen. '
        - content: Azure Application Gateway-WAF
          isCorrect: false
          incorrectExplanation: 'Application Gateway-WAF kann verwendet werden, um Ihre Dienste vor Angriffen wie Einschleusung von XSS- und SQL-Befehlen mit Internetzugriff zu schützen.'
        - content: Azure Disk Encryption
          isCorrect: true
          correctExplanation: 'Azure Disk Encryption Ihre VHDs des virtuellen Computers vor gefährdungen geschützt, aber es bietet keinen Schutz vor netzwerkbasierten Angriffen.'
        - content: Virtuelles Netzwerkgerät
          isCorrect: false
          incorrectExplanation: Virtuelle Netzwerkgeräte können angepasste Netzwerkzugriffsschutz für Ihre Internet zugängliche Ressourcen bereitstellen.