### YamlMime:ModuleUnit
uid: learn.store-app-data-with-azure-blob-storage.5-configure-and-initialize-the-client-library
title: Configure and initialize the client library
metadata:
  title: Configure and initialize the client library
  description: Configure and initialize the client library
  ms.date: 09/24/2018
  #TODO: Update with real author name.
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 10
interactive: bash-editor
azureSandbox: true
content: |
  [!include[](includes/5-configure-and-initialize-the-client-library.md)]