### YamlMime:ModuleUnit
uid: learn.store-app-data-with-azure-blob-storage.5-configure-and-initialize-the-client-library
title: <span data-ttu-id="c1835-101">Konfigurieren und Initialisieren der Clientbibliothek</span><span class="sxs-lookup"><span data-stu-id="c1835-101">Configure and initialize the client library</span></span>
metadata:
  title: <span data-ttu-id="c1835-102">Konfigurieren und Initialisieren der Clientbibliothek</span><span class="sxs-lookup"><span data-stu-id="c1835-102">Configure and initialize the client library</span></span>
  description: <span data-ttu-id="c1835-103">Konfigurieren und Initialisieren der Clientbibliothek</span><span class="sxs-lookup"><span data-stu-id="c1835-103">Configure and initialize the client library</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: bedd297c48ead2c2aadba57e57e3bb8b965344fb
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45755761"
durationInMinutes: 10
interactive: bash-editor
azureSandbox: true
content: '[!include[](includes/5-configure-and-initialize-the-client-library.md)]'
