### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.1-create-azure-iot-central-application
title: Erstellen einer Azure IoT Central-Anwendung
metadata:
  title: Erstellen einer Azure IoT Central-Anwendung
  description: Erstellen einer Azure IoT Central-Anwendung
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 98e9a83d594bc3611f3048909b7d238ea289901e
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45774546"
durationInMinutes: 5
content: '[!include[](includes/1-create-azure-iot-central-application.md)]'
