### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.1-create-azure-iot-central-application
title: Erstellen einer Azure IoT Central-Anwendung
metadata:
  title: Erstellen einer Azure IoT Central-Anwendung
  description: Erstellen einer Azure IoT Central-Anwendung
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 98e9a83d594bc3611f3048909b7d238ea289901e
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47137823"
durationInMinutes: 5
content: '[!include[](includes/1-create-azure-iot-central-application.md)]'
