### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.1-create-azure-iot-central-application
title: <span data-ttu-id="881b9-101">Erstellen einer Azure IoT Central-Anwendung</span><span class="sxs-lookup"><span data-stu-id="881b9-101">Create an Azure IoT Central application</span></span>
metadata:
  title: <span data-ttu-id="881b9-102">Erstellen einer Azure IoT Central-Anwendung</span><span class="sxs-lookup"><span data-stu-id="881b9-102">Create an Azure IoT Central application</span></span>
  description: <span data-ttu-id="881b9-103">Erstellen einer Azure IoT Central-Anwendung</span><span class="sxs-lookup"><span data-stu-id="881b9-103">Create an Azure IoT Central application</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 98e9a83d594bc3611f3048909b7d238ea289901e
  ms.sourcegitcommit: 8a009788ee73c5d7caa6cd4f1105260c5cc9b846
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/22/2018
  ms.locfileid: "46569863"
durationInMinutes: 5
content: '[!include[](includes/1-create-azure-iot-central-application.md)]'
