### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.3-connect-your-application-to-simulator
title: Verbinden Ihrer simulierten Kaffeemaschine mit der Anwendung
metadata:
  title: Verbinden Ihrer simulierten Kaffeemaschine mit der Anwendung
  description: Verbinden Ihrer simulierten Kaffeemaschine mit der Anwendung
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 5e1c175df222a53ef2cd352fbd12feceabe25fad
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45764363"
durationInMinutes: 5
content: '[!include[](includes/3-connect-your-application-to-simulator.md)]'
