### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.5-configure-rules-and-actions
title: <span data-ttu-id="083db-101">Konfigurieren von Regeln und Aktionen zum Überwachen Ihrer Kaffeemaschine</span><span class="sxs-lookup"><span data-stu-id="083db-101">Configure rules and actions to monitor your coffee machine</span></span>
metadata:
  title: <span data-ttu-id="083db-102">Konfigurieren von Regeln und Aktionen zum Überwachen Ihrer Kaffeemaschine</span><span class="sxs-lookup"><span data-stu-id="083db-102">Configure rules and actions to monitor your coffee machine</span></span>
  description: <span data-ttu-id="083db-103">Konfigurieren von Regeln und Aktionen zum Überwachen Ihrer Kaffeemaschine</span><span class="sxs-lookup"><span data-stu-id="083db-103">Configure rules and actions to monitor your coffee machine</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 5a6343fe6bbbe47ec15d343ce3e448315a27f606
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44232794"
durationInMinutes: 12
content: '[!include[](includes/5-configure-rules-and-actions.md)]'
