### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.5-configure-rules-and-actions
title: <span data-ttu-id="2a4a2-101">Konfigurieren von Regeln und Aktionen zum Überwachen Ihrer Kaffeemaschine</span><span class="sxs-lookup"><span data-stu-id="2a4a2-101">Configure rules and actions to monitor your coffee machine</span></span>
metadata:
  title: <span data-ttu-id="2a4a2-102">Konfigurieren von Regeln und Aktionen zum Überwachen Ihrer Kaffeemaschine</span><span class="sxs-lookup"><span data-stu-id="2a4a2-102">Configure rules and actions to monitor your coffee machine</span></span>
  description: <span data-ttu-id="2a4a2-103">Konfigurieren von Regeln und Aktionen zum Überwachen Ihrer Kaffeemaschine</span><span class="sxs-lookup"><span data-stu-id="2a4a2-103">Configure rules and actions to monitor your coffee machine</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 5a6343fe6bbbe47ec15d343ce3e448315a27f606
  ms.sourcegitcommit: 8a009788ee73c5d7caa6cd4f1105260c5cc9b846
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/22/2018
  ms.locfileid: "46569975"
durationInMinutes: 12
content: '[!include[](includes/5-configure-rules-and-actions.md)]'
