### YamlMime:ModuleUnit
uid: learn.make-your-virtual-machines-highly-available.4-configure-a-load-balancer-in-azure
title: Configure a load balancer in Azure
metadata:
  title: Configure a load balancer in Azure
  description: Configure a load balancer in Azure
  ms.date: 09/24/2018
  #TODO: Update with real author name.
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 5
content: |
  [!include[](includes/4-configure-a-load-balancer-in-azure.md)]