### YamlMime:ModuleUnit
uid: learn.make-your-virtual-machines-highly-available.5-configure-a-load-balancer-in-azure
title: Konfigurieren eines Lastenausgleichs in Azure
metadata:
  title: Konfigurieren eines Lastenausgleichs in Azure
  description: Konfigurieren eines Lastenausgleichs in Azure
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: f0ac81ae3551f12da7b649c77332c92b51ba3089
  ms.sourcegitcommit: 58e9d7fbb111af9b27ed819e4b79ba4a4e6e8a9c
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/21/2018
  ms.locfileid: "46513211"
durationInMinutes: 5
content: '[!include[](includes/5-configure-a-load-balancer-in-azure.md)]'
