### YamlMime:ModuleUnit
uid: learn.make-your-virtual-machines-highly-available.5-exercise–configure-a-load-balancer-in-azure
title: Exercise - Configure a load balancer in Azure
metadata:
  title: Exercise - Configure a load balancer in Azure
  description: Exercise - Configure a load balancer in Azure
  ms.date: 09/24/2018
  #TODO: Update with real author name.
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 10
content: |
  [!include[](includes/5-exercise–configure-a-load-balancer-in-azure.md)]