### YamlMime:ModuleUnit
uid: learn.make-your-virtual-machines-highly-available.6-exercise-configure-a-load-balancer-in-azure
title: 'Übung: Konfigurieren eines Lastenausgleichs in Azure'
metadata:
  title: 'Übung: Konfigurieren eines Lastenausgleichs in Azure'
  description: 'Übung: Konfigurieren eines Lastenausgleichs in Azure'
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: d653a821bf0b0522ca085de5af23f830e6d24041
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47137655"
azureSandbox: true
durationInMinutes: 15
content: '[!include[](includes/6-exercise-configure-a-load-balancer-in-azure.md)]'
