### YamlMime:ModuleUnit
uid: learn.make-your-virtual-machines-highly-available.6-exercise-configure-a-load-balancer-in-azure
title: '<span data-ttu-id="e74a8-101">Übung: Konfigurieren eines Lastenausgleichs in Azure</span><span class="sxs-lookup"><span data-stu-id="e74a8-101">Exercise - Configure a load balancer in Azure</span></span>'
metadata:
  title: '<span data-ttu-id="e74a8-102">Übung: Konfigurieren eines Lastenausgleichs in Azure</span><span class="sxs-lookup"><span data-stu-id="e74a8-102">Exercise - Configure a load balancer in Azure</span></span>'
  description: '<span data-ttu-id="e74a8-103">Übung: Konfigurieren eines Lastenausgleichs in Azure</span><span class="sxs-lookup"><span data-stu-id="e74a8-103">Exercise - Configure a load balancer in Azure</span></span>'
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: d653a821bf0b0522ca085de5af23f830e6d24041
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47137655"
azureSandbox: true
durationInMinutes: 15
content: '[!include[](includes/6-exercise-configure-a-load-balancer-in-azure.md)]'
