### YamlMime:ModuleUnit
uid: learn.design-a-great-azure-architecture.3-design-for-security
title: Sicherheitsorientierter Entwurf
metadata:
  title: Sicherheitsorientierter Entwurf
  description: Sicherheitsorientierter Entwurf
  ms.openlocfilehash: 394af78966bfde3b2c82e2af17a10bb8680fc659
  ms.sourcegitcommit: 09425147d998035edf9d2d36006a54d85e3cf75d
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "43847247"
durationInMinutes: 10
content: >
  [!include[](includes/3-design-for-security.md)]
quiz:
  title: 'Wissenstest: Sicherheitsorientierter Entwurf'
  questions:
  - content: Für welche der folgenden Datentypen sollten möglicherweise Sicherheitsmaßnahmen vorgesehen werden?
    choices:
    - content: Kundendaten, die persönliche Informationen enthalten.
      isCorrect: false
      incorrectExplanation: Es ist wichtig, entsprechende Schutzmaßnahmen für diese Daten bereitzustellen. Dies ist aber nicht die einzige richtige Wahl.
    - content: Finanzdaten, die Geschäftsvorgänge unterstützen.
      isCorrect: false
      incorrectExplanation: Es ist wichtig, entsprechende Schutzmaßnahmen für diese Daten bereitzustellen. Dies ist aber nicht die einzige richtige Wahl.
    - content: Daten, die geistiges Eigentum enthalten.
      isCorrect: false
      incorrectExplanation: Es ist wichtig, entsprechende Schutzmaßnahmen für diese Daten bereitzustellen. Dies ist aber nicht die einzige richtige Wahl.
    - content: Für alle oben genannten Datentypen sind möglicherweise Sicherheitsmaßnahmen erforderlich.
      isCorrect: true
      correctExplanation: Alle oben genannten Datentypen können möglicherweise zusätzliche Sicherheitsvorkehrungen erfordern.
  - content: Welches der folgenden Szenarien ist ein Beispiel für einen Angriff, der in der Umkreisebene auftreten kann?
    choices:
    - content: Offengelegte Anmeldeinformationen, die online gepostet werden.
      isCorrect: false
      incorrectExplanation: Offengelegte Anmeldeinformationen stellen ein großes Risiko für eine Organisation dar, sie sind aber kein Umkreisangriff.
    - content: Ein SYN Flood-Angriff.
      isCorrect: true
      correctExplanation: SYN Flood-Angriffe sind Denial-of-Service-Angriffe, die häufig im Umkreisnetzwerk auftreten.
    - content: Die nicht autorisierte Verwendung von Zugangscodes, um Einlass in ein Datencenter zu erlangen.
      isCorrect: false
      incorrectExplanation: Die nicht autorisierte Verwendung von Zugangscodes ist ein Angriff der physischen Ebene.
    - content: Ransomware, die die Datenträger eines virtuellen Computers verschlüsselt
      isCorrect: false
      incorrectExplanation: Ransomwareangriffe sind Angriffe der VM-/Computeebene.
