### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: Exercise - Create an ASP.NET Core application on Linux
metadata:
  title: Exercise - Create an ASP.NET Core application on Linux
  description: Exercise - Create an ASP.NET Core application on Linux
  ms.date: 09/24/2018
  #TODO: Update with real author name.
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 10
content: |
  [!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]