### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: <span data-ttu-id="f9890-101">Übung – Erstellen einer ASP.NET Core-Anwendung unter Linux</span><span class="sxs-lookup"><span data-stu-id="f9890-101">Exercise - Create an ASP.NET Core application on Linux</span></span>
metadata:
  title: <span data-ttu-id="f9890-102">Übung – Erstellen einer ASP.NET Core-Anwendung unter Linux</span><span class="sxs-lookup"><span data-stu-id="f9890-102">Exercise - Create an ASP.NET Core application on Linux</span></span>
  description: <span data-ttu-id="f9890-103">Übung – Erstellen einer ASP.NET Core-Anwendung unter Linux</span><span class="sxs-lookup"><span data-stu-id="f9890-103">Exercise - Create an ASP.NET Core application on Linux</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: d568d2d92f827fea2713d8c79f29fc646033d588
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44234953"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
