### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
interactive: bash
metadata:
  title: Festlegen von Umgebungsvariablen
  description: Legen Sie Umgebungsvariablen in Azure Container Instances fest.
  ms.openlocfilehash: 921168a568e52b47ff347521fff4969213d0fa88
  ms.sourcegitcommit: 56db32ad6f98b7d769f2b1201825d4f6d9b7362d
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43727409"
title: Festlegen von Umgebungsvariablen
durationInMinutes: 10
content: '[!include[](includes/4-use-environment-variables.md)]'
