### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
interactive: bash
metadata:
  title: <span data-ttu-id="42f5c-101">Festlegen von Umgebungsvariablen</span><span class="sxs-lookup"><span data-stu-id="42f5c-101">Set environment variables</span></span>
  description: <span data-ttu-id="42f5c-102">Legen Sie Umgebungsvariablen in Container Instances fest.</span><span class="sxs-lookup"><span data-stu-id="42f5c-102">Set environment variables in Contianer Instances.</span></span>
  displayType: one-column
  ms.openlocfilehash: 1911822589f7120ed0cddd9a1c807a76c045f75c
  ms.sourcegitcommit: 926510a198d738c5726081f6d7994fe9b6fc6edb
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43181124"
title: <span data-ttu-id="42f5c-103">Festlegen von Umgebungsvariablen</span><span class="sxs-lookup"><span data-stu-id="42f5c-103">Set environment variables</span></span>
durationInMinutes: 10
content: '[!include[](includes/4-use-environment-variables.md)]'
