### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-app-service.5-exercise-create-an-asp.net-core-web-application-on-linux
title: <span data-ttu-id="588af-101">Übung – Erstellen einer ASP.NET Core-Anwendung unter Linux</span><span class="sxs-lookup"><span data-stu-id="588af-101">Exercise - Create an ASP.NET Core application on Linux</span></span>
metadata:
  title: <span data-ttu-id="588af-102">Übung – Erstellen einer ASP.NET Core-Anwendung unter Linux</span><span class="sxs-lookup"><span data-stu-id="588af-102">Exercise - Create an ASP.NET Core application on Linux</span></span>
  description: <span data-ttu-id="588af-103">Übung – Erstellen einer ASP.NET Core-Anwendung unter Linux</span><span class="sxs-lookup"><span data-stu-id="588af-103">Exercise - Create an ASP.NET Core application on Linux</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 3c73c9ee2da417fcbfb91cc5beeae6a13659c5e7
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45776535"
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
