### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-app-service.5-exercise-create-an-asp.net-core-web-application-on-linux
title: Übung – Erstellen einer ASP.NET Core-Anwendung unter Linux
metadata:
  title: Übung – Erstellen einer ASP.NET Core-Anwendung unter Linux
  description: Übung – Erstellen einer ASP.NET Core-Anwendung unter Linux
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 10
content: |
  [!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]