### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: <span data-ttu-id="68418-101">Übung – Erstellen einer ASP.NET Core-Anwendung unter Linux</span><span class="sxs-lookup"><span data-stu-id="68418-101">Exercise - Create an ASP.NET Core application on Linux</span></span>
metadata:
  title: <span data-ttu-id="68418-102">Übung – Erstellen einer ASP.NET Core-Anwendung unter Linux</span><span class="sxs-lookup"><span data-stu-id="68418-102">Exercise - Create an ASP.NET Core application on Linux</span></span>
  description: <span data-ttu-id="68418-103">Übung – Erstellen einer ASP.NET Core-Anwendung unter Linux</span><span class="sxs-lookup"><span data-stu-id="68418-103">Exercise - Create an ASP.NET Core application on Linux</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 1755b3e9fde0c7c3e4f812551960035a76f23c88
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46344492"
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
