### YamlMime:ModuleUnit
uid: learn.design-for-performance-and-scalability.5-identify-performance-bottlenecks-in-your-application
title: Erkennen von Leistungsengpässen in Ihrer Anwendung
metadata:
  title: Erkennen von Leistungsengpässen in Ihrer Anwendung
  description: In dieser Einheit wird erörtert, wie Sie Leistungsengpässe in Ihrer Anwendung erkennen.
  ms.openlocfilehash: 0b5ab3a983a4b3dfc3a76c914b6a565f3ee7ed2c
  ms.sourcegitcommit: 926510a198d738c5726081f6d7994fe9b6fc6edb
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43180823"
durationInMinutes: 5
content: >
  [!include[](includes/5-identify-performance-bottlenecks-in-your-application.md)]
quiz:
  title: 'Wissenstest: Erkennen von Leistungsengpässen in Ihrer Anwendung'
  questions:
  - content: Welche der folgenden Aussagen beschreibt Application Insights am besten?
    choices:
    - content: Einzelne Verwaltungskonsole für Überwachungsanforderungen in Azure
      isCorrect: false
    - content: Implementierung der Überwachungsmuster für den Integritätsendpunkt
      isCorrect: false
    - content: Arbeitsbereich, in dem die Sammlung von Protokollen in der gesamten Infrastruktur und Anwendungen aktiviert wird
      isCorrect: false
    - content: Dienst zum Überwachen von Verfügbarkeit, Leistung und Nutzung von Webanwendungen
      isCorrect: true
  - content: Sie können Log Analytics verwenden, um benutzerdefinierte Protokolle und Metriken nachzuverfolgen.
    choices:
    - content: "True"
      isCorrect: true
    - content: "False"
      isCorrect: false
