### YamlMime:ModuleUnit
uid: learn.design-for-performance-and-scalability.5-identify-performance-bottlenecks-in-your-application
title: <span data-ttu-id="92de6-101">Erkennen von Leistungsengpässen in Ihrer Anwendung</span><span class="sxs-lookup"><span data-stu-id="92de6-101">Identify performance bottlenecks in your application</span></span>
metadata:
  title: <span data-ttu-id="92de6-102">Erkennen von Leistungsengpässen in Ihrer Anwendung</span><span class="sxs-lookup"><span data-stu-id="92de6-102">Identify performance bottlenecks in your application</span></span>
  description: <span data-ttu-id="92de6-103">In dieser Einheit wird erörtert, wie Sie Leistungsengpässe in Ihrer Anwendung erkennen.</span><span class="sxs-lookup"><span data-stu-id="92de6-103">In this unit we'll discuss how to identify performance bottlenecks in your application</span></span>
  ms.openlocfilehash: 0b5ab3a983a4b3dfc3a76c914b6a565f3ee7ed2c
  ms.sourcegitcommit: 926510a198d738c5726081f6d7994fe9b6fc6edb
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43180823"
durationInMinutes: 5
content: >
  [!include[](includes/5-identify-performance-bottlenecks-in-your-application.md)]
quiz:
  title: '<span data-ttu-id="92de6-104">Wissenstest: Erkennen von Leistungsengpässen in Ihrer Anwendung</span><span class="sxs-lookup"><span data-stu-id="92de6-104">Knowledge Check - Identify performance bottlenecks in your application</span></span>'
  questions:
  - content: <span data-ttu-id="92de6-105">Welche der folgenden Aussagen beschreibt Application Insights am besten?</span><span class="sxs-lookup"><span data-stu-id="92de6-105">Which of the following best describes Application Insights?</span></span>
    choices:
    - content: <span data-ttu-id="92de6-106">Einzelne Verwaltungskonsole für Überwachungsanforderungen in Azure</span><span class="sxs-lookup"><span data-stu-id="92de6-106">A single pane of glass for our monitoring needs in Azure</span></span>
      isCorrect: false
    - content: <span data-ttu-id="92de6-107">Implementierung der Überwachungsmuster für den Integritätsendpunkt</span><span class="sxs-lookup"><span data-stu-id="92de6-107">An implementation of the health endpoint monitoring pattern</span></span>
      isCorrect: false
    - content: <span data-ttu-id="92de6-108">Arbeitsbereich, in dem die Sammlung von Protokollen in der gesamten Infrastruktur und Anwendungen aktiviert wird</span><span class="sxs-lookup"><span data-stu-id="92de6-108">A workspace to enable collection of logs across infrastructure and applications</span></span>
      isCorrect: false
    - content: <span data-ttu-id="92de6-109">Dienst zum Überwachen von Verfügbarkeit, Leistung und Nutzung von Webanwendungen</span><span class="sxs-lookup"><span data-stu-id="92de6-109">A service to monitor availability, performance, and usage of web applications</span></span>
      isCorrect: true
  - content: <span data-ttu-id="92de6-110">Sie können Log Analytics verwenden, um benutzerdefinierte Protokolle und Metriken nachzuverfolgen.</span><span class="sxs-lookup"><span data-stu-id="92de6-110">You can use Log Analytics to track custom logs and metrics.</span></span>
    choices:
    - content: <span data-ttu-id="92de6-111">True</span><span class="sxs-lookup"><span data-stu-id="92de6-111">True</span></span>
      isCorrect: true
    - content: <span data-ttu-id="92de6-112">False</span><span class="sxs-lookup"><span data-stu-id="92de6-112">False</span></span>
      isCorrect: false
