### YamlMime:ModuleUnit
uid: learn.design-for-security.6-network-security
title: Netzwerksicherheit
metadata:
  title: Netzwerksicherheit
  description: In dieser Einheit wird erörtert, wie Sie Ihre Netzwerkinfrastruktur schützen.
  ms.openlocfilehash: 290415bd679f608fec17d276d64dff967d9252bb
  ms.sourcegitcommit: 56db32ad6f98b7d769f2b1201825d4f6d9b7362d
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43728361"
durationInMinutes: 5
content: >
  [!include[](includes/6-network-security.md)]
quiz:
  title: 'Wissenstest: Netzwerksicherheit'
  questions:
  - content: Welche der folgenden Übertragungen können mit Azure-NSGs abgesichert werden?
    choices:
    - content: Übertragungen zwischen virtuellen Computern und dem Internet
      isCorrect: false
      incorrectExplanation: Mit NSGs kann diese Übertragung zwar abgesichert werden, doch dies ist nicht die einzige richtige Antwortmöglichkeit.
    - content: Übertragungen zwischen virtuellen Computern innerhalb eines VNet
      isCorrect: false
      incorrectExplanation: Mit NSGs kann diese Übertragung zwar abgesichert werden, doch dies ist nicht die einzige richtige Antwortmöglichkeit.
    - content: Übertragungen zwischen Systemen in einem lokalen Netzwerk
      isCorrect: false
      incorrectExplanation: Mit NSGs kann diese Übertragung zwar abgesichert werden, doch dies ist nicht die einzige richtige Antwortmöglichkeit.
    - content: Alle oben genannten Möglichkeiten
      isCorrect: true
      correctExplanation: Mit NSGs können alle der oben genannten Übertragungen abgesichert werden.
  - content: Welche der folgenden Methoden eignet sich nicht zum Schutz von Diensten mit Internetzugriff vor Netzwerkangriffen?
    choices:
    - content: Azure DDoS
      isCorrect: false
      incorrectExplanation: 'Mit Azure DDoS können mit dem Internet verbundene Dienste vor einem DoS-Angriff geschützt werden. '
    - content: Azure Application Gateway-WAF
      isCorrect: false
      incorrectExplanation: Mit Application Gateway-WAF können mit dem Internet verbundene Dienste vor XSS-Angriffen und SQL Injection geschützt werden.
    - content: Azure Disk Encryption
      isCorrect: true
      correctExplanation: Mit Azure Disk Encryption werden die VHDs eines virtuellen Computers geschützt, falls diese ohne Berechtigung zugänglich gemacht werden. Der Dienst bietet aber keinen Schutz vor Netzwerkangriffen.
    - content: Virtuelles Netzwerkgerät
      isCorrect: false
      incorrectExplanation: Virtuelle Netzwerkgeräte stellen anpassbaren Netzwerkzugriffsschutz für Ressourcen bereit, die mit dem Internet verbunden sind.
