### YamlMime:ModuleUnit
uid: learn.design-for-security.6-network-security
title: Netzwerksicherheit
metadata:
  title: Netzwerksicherheit
  description: In dieser Einheit wird erörtert, wie Sie Ihre Netzwerkinfrastruktur schützen.
  ms.openlocfilehash: f98e9f24b46119fda8be58fb4a06f8f15d60ed66
  ms.sourcegitcommit: 1663afb13d55c1fce5f2dc4c0f78ef2d74902c33
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 08/31/2018
  ms.locfileid: "43366926"
durationInMinutes: 5
content: >
  [!include[](includes/6-network-security.md)]
quiz:
  title: 'Wissenstest: Netzwerksicherheit'
  questions:
  - content: Bei der Ausführung von Webanwendungen in Azure App Service ist Ihre Anwendung vollständig sicher, und es bedarf keiner zusätzlichen Sicherheitsmaßnahmen.
    choices:
    - content: Richtig
      isCorrect: false
    - content: Falsch
      isCorrect: true
  - content: Welche der folgenden ist keine Methode zum Schutz von Diensten mit Internetzugriff vor Netzwerkangriffen?
    choices:
    - content: Azure DDoS
      isCorrect: false
    - content: Azure Application Gateway-WAF
      isCorrect: false
    - content: Azure Disk Encryption
      isCorrect: true
    - content: Virtuelles Netzwerkgerät
      isCorrect: false
